### ISSUE TITLE
bip-schnorr/taproot agree on terminology of points

### ISSUE THREAD

**Issue by jonasnick** [sipa/bips#118]
In https://github.com/sipa/bips/pull/116#issuecomment-549230288 @gmaxwell brought up a new argument against using `is_positive` for points with a square Y coordinate. Alternative suggestions are `is_square` and `has_square_y`. I'm opening an issue because this would affect a few different files:

* bip-schnorr.md
* bip-taproot.md
* bip-schnorr/reference.py
* bip-schnorr/test-vectors.csv
* bip-schnorr/test-vectors.py
* https://github.com/bitcoin-core/secp256k1/pull/558/commits

Also, I noticed that bip-taproot.md hasn't been updated in a while and still refers to quadratic residues and an `is_quad()` function which isn't defined.

I've warmed up to the idea of using `has_square_y` for code and for the bip. In general I still like the positive/negative terminology because it's way easier to say in english than "a point whose Y coordinate is a square" (which we use 4 times in bip-schnorr and once in bip-taproot). But perhaps that's just something that doesn't need to be defined in the bip.

**Comment by ajtowns** [comment]
+1 -- Positive seems fine as a shorthand for people doing maths, but not particularly helpful for anyone without a background in abstract algebra?

Overloading `is_square` to work for both points and ints would more or less match the overloading of `bytes`... but `has_square_y` is pretty unambiguous.

**Comment by real-or-random** [comment]
I think "positive" is just good as a shorthand but it's not even good for people with a background in algebra -- this definition is non-standard.

re overloading: "square" is a standard term for field elements but not for points, so I wouldn't use "square" for points.

Another possibilty would be to use a term that refers to the purpose (instead of the mathematical properties). We could call these points "valid points" or "pubkey points" or similar. But I find none of those really convincing. Then I think "has a square y" is just better.

**Comment by elichai** [comment]
idk. all of them will probably be confusing for new people trying to learn what's going on here.
anyway. if we're not going to use specifically quadratic residue / Some symbol then I don't have a strong opinion in the exact terminology (as it will anyway require to look up, see that it means QR, and then lookup QR)
(a third idea for fun is `y_has_sqrt`)

**Comment by sipa** [comment]
I like is_square for field elements, and has_square_y for points.

**Comment by sipa** [comment]
See #124.

**Comment by sipa** [comment]
Fixed by #124.
