### ISSUE TITLE
bip-schnorr: consider synthetic nonces

### ISSUE THREAD

**Issue by real-or-random** [sipa/bips#95]
@trevp proposes "synthetic nonces" [1], which means generating the nonce from deterministically derived "randomness" and real randomness. This has hardly any disadvantages over deterministic nonces but comes with the benefit of protection against some kinds of fault injection attacks, e.g., if an attacker can inject a fault in the computation of the main signature hash, then it can happen that you leak the private key if you sign the same message twice (same deterministic nonce, different hash). They provide some other minor benefits, too, see Trevor's email for details. 

[1] https://moderncrypto.org/mail-archive/curves/2017/000925.html (see in particular the section on "nonce randomization")
[2] https://research.kudelskisecurity.com/2017/10/04/defeating-eddsa-with-faults/

**Comment by real-or-random** [comment]
One particular advantage for us would be that the security of the nonce generation algorithm doesn't break down immediately if someone naively uses it in MuSig or similar schemes.

**Comment by gmaxwell** [comment]
libsecp256k1 supports doing this today with the existing nonce function taking aux data (it's even a feature of RFC6979 but not well promoted).

The disadvantage is that you lose the 'audibility' of implementation based on checking that you get the same signatures-- which might help convince you that a sidechannel leak is less likely.   But that audibility is virtually unused in practice, and the protection it provides is very thin (e.g. leak the keys but only on one in 100 signatures or only if the input message has certain properties).  Concerns about leaky signers would better be addressed by nonce functions that are leakage resistant.

I still think it would be a big step forward if bip-schnorr's default nonce function would be one that is easily made leakage resistant (e.g. by moving a couple steps to the warden host).

**Comment by real-or-random** [comment]
> Concerns about leaky signers would better be addressed by nonce functions that are leakage resistant and/or multisig.
> 
> I still think it would be a big step forward if bip-schnorr's default nonce function would be one that is easily made leakage resistant (e.g. by moving a couple steps to the warden host).

Sorry I think I llack some background here. What's a leakage resistant nonce function? What's a warden host?

**Comment by gmaxwell** [comment]
Consider a hardware wallet.  Maybe it's evil and sometimes uses ECDH to pick nonces which are deterministic ... and known to an attacker (in fact it can also slowly exfiltrate a master key at the same time).  The tamper resistant opacity of an HSM or Hardware wallet makes it also a good place to hide malicious code.

Seems like a pretty attractive business for attackers once the lower hanging fruit is picked: make convincing cloned hardware wallets with backdoored firmware, sell on ebay for $1 less than the real thing. [At the moment right now these attackers are just slipping in a piece of paper that says "Your pregenerated seed is ...." but eventually the easier suckers will run out...]

The bummer is that you got the HSM/HW wallet thing to be more secure but became less secure because it made you an easily identified target for a supply chain attack.

How can you defend against that?   You have an interaction with the host (warden, like a prison warden snooping the prisoner mail to make sure they're not plotting an escape) so that the host can randomize the signature's nonce.

I believe the secure protocol I like is where the host picks a random value x, sends a commitment to it H(x) to the HW wallet with the data to sign.  The HW wallet generates a nonce using 6979 with the host's commitment as one of the inputs (important step, otherwise the host can replay with different commitments).  The HW wallet sends R to the host, the host sends x back to the HW wallet,  hw wallet checks the commitment and tweaks its R by adding x,  so the signature is signed with k' = k+x and has R'  = R + xG.  The host can check that the final signature has been tweaked.

Now the hardware wallet has no real sidechannel to the outside world anymore unless the host co-operates.
 
What if the HW wallet and host are both evil?  oh well, can't win 'em all... but that's a much harder attack to pull off--- and the expense of backdooring a lot of HW wallets will be less worth it if it does no good unless the host is compromised too.

**Comment by real-or-random** [comment]
Ah okay sure, I was aware of that issue and the protocol that solves it.

> I still think it would be a big step forward if bip-schnorr's default nonce function would be one that is easily made leakage resistant (e.g. by moving a couple steps to the warden host).

Do you have a concrete function in mind? I'm not sure if optimizing the default function in bip-schnorr is a good idea. It seems to me that the additional effort to implement the interactive protocol does not depend a lot on which function is used to generate k and x.

**Comment by gmaxwell** [comment]
It's as simple as setting up the interactive protocol and to make it interactive you run two of the functions (generate commitment, check signature) on the warden instead of the signer and copy the buffer between them.

I think the way the BIP specifies things today it will actually make it harder than it is with ecdsa to get people to implement the interactive protocol because doing so will "violate the bip".

**Comment by sipa** [comment]
I believe we need to separate the "Signing" section into a "Default signing algorithm", and an "Alternative signing algorithms" section, where the latter can list that other compatible signing algorithms exist (e.g. MuSig, which for now can't use derandomized nonces), that additional entropy can be fed into the default function, and that hardening approaches are possible.

**Comment by real-or-random** [comment]
Indeed, this (or something similar) sounds good. This is related to #88 then.

**Comment by gmaxwell** [comment]
Sounds fine to me.

**Comment by sipa** [comment]
See #113.
